---
- name: Deploy container in kubernetes
  hosts: k8master
  become: yes
  tasks:
    - name: Pushing kubernetes scriptfile file into kubernetes master server
      copy:
        src: /tmp/project1/kubernetesscript.sh
        dest: /tmp/project1/kubernetesscript.sh
    - name: Pushing Kubernetes service file into kubernetes master server
      copy:
        src: /tmp/project1/service.yml
        dest: /tmp/project1/service.yml
    - name: Pushing kubernetes pod creation file into Docker server
      copy:
        src: /tmp/project1/pod.yml
        dest: /tmp/project1/pod.yml
    - name: Setting permissions for the script file
      file:
        path: /tmp/project1/kubernetesscript.sh
        mode: '0777'
      become: yes
    - name: Executing Dockerfile on Docker server
      shell: /tmp/project1/kubernetesscript.sh
      become: yes
